-- Watch industry jargon seed data
-- Common abbreviations used in WhatsApp watch trading groups

INSERT INTO jargon_dictionary (acronym, expansion, industry, source, confidence, verified)
VALUES
    ('FS', 'Full Set (box, papers, warranty card)', 'watches', 'seed', 1.0, true),
    ('WO', 'Watch Only (no box or papers)', 'watches', 'seed', 1.0, true),
    ('BNIB', 'Brand New In Box', 'watches', 'seed', 1.0, true),
    ('AD', 'Authorized Dealer', 'watches', 'seed', 1.0, true),
    ('RR', 'Retail Ready', 'watches', 'seed', 1.0, true),
    ('WG', 'White Gold', 'watches', 'seed', 1.0, true),
    ('YG', 'Yellow Gold', 'watches', 'seed', 1.0, true),
    ('RG', 'Rose Gold', 'watches', 'seed', 1.0, true),
    ('SS', 'Stainless Steel', 'watches', 'seed', 1.0, true),
    ('TT', 'Two-Tone (steel and gold)', 'watches', 'seed', 1.0, true),
    ('WTB', 'Want To Buy', 'watches', 'seed', 1.0, true),
    ('WTS', 'Want To Sell', 'watches', 'seed', 1.0, true),
    ('WTT', 'Want To Trade', 'watches', 'seed', 1.0, true),
    ('ISO', 'In Search Of', 'watches', 'seed', 1.0, true),
    ('NOS', 'New Old Stock', 'watches', 'seed', 1.0, true),
    ('B&P', 'Box and Papers', 'watches', 'seed', 1.0, true),
    ('OEM', 'Original Equipment Manufacturer', 'watches', 'seed', 1.0, true),
    ('NH', 'No Hours (unworn)', 'watches', 'seed', 1.0, true),
    ('LNIB', 'Like New In Box', 'watches', 'seed', 1.0, true),
    ('RO', 'Royal Oak (Audemars Piguet)', 'watches', 'seed', 1.0, true),
    ('ROO', 'Royal Oak Offshore (Audemars Piguet)', 'watches', 'seed', 1.0, true),
    ('Sub', 'Submariner (Rolex)', 'watches', 'seed', 1.0, true),
    ('DJ', 'Datejust (Rolex)', 'watches', 'seed', 1.0, true),
    ('DD', 'Day-Date (Rolex)', 'watches', 'seed', 1.0, true),
    ('GMT', 'GMT-Master (Rolex)', 'watches', 'seed', 1.0, true),
    ('PP', 'Patek Philippe', 'watches', 'seed', 1.0, true),
    ('AP', 'Audemars Piguet', 'watches', 'seed', 1.0, true),
    ('RM', 'Richard Mille', 'watches', 'seed', 1.0, true),
    ('JLC', 'Jaeger-LeCoultre', 'watches', 'seed', 1.0, true),
    ('VC', 'Vacheron Constantin', 'watches', 'seed', 1.0, true),
    ('IWC', 'International Watch Company', 'watches', 'seed', 1.0, true),
    ('ALS', 'A. Lange & Sohne', 'watches', 'seed', 1.0, true),
    ('MSRP', 'Manufacturer Suggested Retail Price', 'watches', 'seed', 1.0, true),
    ('Hulk', 'Rolex Submariner green dial/bezel (116610LV)', 'watches', 'seed', 1.0, true),
    ('Batman', 'Rolex GMT-Master II blue/black bezel', 'watches', 'seed', 1.0, true),
    ('Pepsi', 'Rolex GMT-Master II red/blue bezel', 'watches', 'seed', 1.0, true),
    ('Coke', 'Rolex GMT-Master II red/black bezel', 'watches', 'seed', 1.0, true),
    ('Panda', 'White dial with black subdials (chronograph)', 'watches', 'seed', 1.0, true),
    ('Tiffany', 'Tiffany blue dial (Rolex OP or similar)', 'watches', 'seed', 1.0, true),
    ('Speedy', 'Omega Speedmaster', 'watches', 'seed', 1.0, true)
ON CONFLICT (acronym, expansion) DO NOTHING;
